### ISSUE TITLE
Search Component

### ISSUE THREAD

**Issue by jtphillips215** [chingu-voyages/v45-tier1-team-07#17]
**__Feature Description__**
As a team, we want to develop a search component allowing users to search meteor strike data so that they can easily review and filter that data. The component must contain the ability to search and reset or clear the search results. It should also include some guidance on how to search or what information can be entered in to search.

**__Major User Stories/tasks__**
- [ ] Link User Story or Task  # 1
- [ ] Link User Story or Task # 2
- [ ] Link Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
