### ISSUE TITLE
Summary Component

### ISSUE THREAD

**Issue by jtphillips215** [chingu-voyages/v45-tier1-team-07#18]
**__Feature Description__**
As a team, we will develop a summary component that displays the total number of meteor strikes and average mass of those strikes while no search is active. We will also display histograms of the number of strikers per year and by meteorite composition.

**__Major User Stories/tasks__**
- [ ] Link User Story or Task  #1
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
