### ISSUE TITLE
Detail Data View Component

### ISSUE THREAD

**Issue by jtphillips215** [chingu-voyages/v45-tier1-team-07#19]
**__Feature Description__**
As a team, we will develop a detail view that will show the user data about selected meteorite strike(s) based on entered search criteria.

**__Major User Stories/tasks__**
- [ ] Link User Story or Task  # 1
- [ ] Link User Story or Task # 2
- [ ] Link Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
